# Site settings
title: 小雅的博客
email: mis_ding@sina.com
description: > # this means to ignore newlines until "baseurl:"
  小雅的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yyyyama.github.io/" # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Xiao ya


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
